### ISSUE TITLE
导入前端web查询的workflow之后，出现了下面的问题，我需要做些什么？

### ISSUE THREAD

**Issue by xuexuguang** [Louiszhai/alfred-workflows#2]
![image](https://user-images.githubusercontent.com/22195079/46590049-f2d0f400-cae2-11e8-889a-7d45417c04cc.png)

**Comment by Louiszhai** [comment]
同级目录下，是存在feedback.py文件的，方便留下qq或微信吗？一起排查下

**Comment by xuexuguang** [comment]
微信 17611527696

**Comment by Eurkidu** [comment]
![default](https://user-images.githubusercontent.com/13271070/47084539-52976f80-d246-11e8-8c0a-ee4beac7513f.png)

相同的报错
alfredTool 目录下并没有 feedback.py 如上图所示
alfred2 目录下有个 feedback.py 文件，不过我想应该不是同一个，尝试粘出来，报了更多的错
@Louiszhai

**Comment by Louiszhai** [comment]
稍等，我更新下，确实少了资源

**Comment by Louiszhai** [comment]
已更新

**Comment by Eurkidu** [comment]
![default](https://user-images.githubusercontent.com/13271070/47127039-fbcd7c80-d2bd-11e8-9409-9c97fc8292e9.png)

输入最后的分号的时候会报错
好像又少了资源 `ImportError: No module named bs4` 详细错误信息如上图所示
@Louiszhai

**Comment by Louiszhai** [comment]
非常抱歉，bs4需要手动安装，我在内置时出现了一些问题，推荐使用如下方式安装：
pip install bs4

**Comment by Eurkidu** [comment]
可以使用了，非常感谢

**Comment by Louiszhai** [comment]
🤝

Eurkidu <notifications@github.com>于2018年10月18日 周四12:08写道：

**Comment by Louiszhai** [comment]
问题已解决
